modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons"

[[mods]]
modId="lostworlds"
version="1.0.0"
displayName="The Lost Worlds"
authors="Main Developer: Willatendo. 3d Artists: Lilly Jooji, DapperDino and bAbA. 2d Artist: Emilosaurus65"

description='''
A 1.16.5 Forge mod that adds dinosaurs, archaeology, and more to the game!
'''
