modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons"

[[mods]]
modId="lostworlds"
version="1.0.0"
displayName="The Lost Worlds"
authors="Main Developer: Willatendo. 3d Artists: Lilly Jooji, DapperDino and bAbA. 2d Artist: Emilosaurus65"

description='''
The Lost Worlds is a Minecraft Dinosaur Mod with the goal of high quality work on the newest verisons of Minecraft! The Lost Worlds adds tonnes of new content from exploring the Lost Worlds like the Permian and Jurassic, to finding fossils underground and extracting them to make new dinosaurs! The Lost Worlds also adds tonnes of Archaeology to the game! Adding a story and lot's to uncover about the Minecraft World.
'''
