modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons"

[[mods]]
modId="lostworlds"
version="1.0.0"
displayName="The Lost Worlds"
authors="Main Developer: Willatendo. Artists: Lilly Jooji, and bAbA. Former Artists: DapperDino"

description='''
A 1.16.5/1.16.3/1.15.2 Forge mod that adds dinosaurs, archaeology, and more to the game!
'''
