package lostworlds.client.screen.fieldguides;

import lostworlds.core.util.ModUtil;
import net.minecraft.util.text.ITextComponent;

public class FieldGuideLang 
{
	public static final ITextComponent DANGER = ModUtil.tTC("field_guide.danger");
	public static final ITextComponent DIET = ModUtil.tTC("field_guide.diet");
	public static final ITextComponent TYPE = ModUtil.tTC("field_guide.type");
	public static final ITextComponent SEX = ModUtil.tTC("field_guide.sex");
	public static final ITextComponent TIME_ERA = ModUtil.tTC("field_guide.time_era");

	public static final ITextComponent SEX_MALE = ModUtil.tTC("field_guide.sex_male");
	public static final ITextComponent SEX_FEMALE = ModUtil.tTC("field_guide.sex_female");

	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_NAME = ModUtil.tTC("procompsognathus.field_guide.name");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_SPECIES_NAME = ModUtil.tTC("procompsognathus.field_guide.species_name");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_ONE = ModUtil.tTC("procompsognathus.field_guide.entry_line_one");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_TWO = ModUtil.tTC("procompsognathus.field_guide.entry_line_two");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_THREE = ModUtil.tTC("procompsognathus.field_guide.entry_line_three");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_FOUR = ModUtil.tTC("procompsognathus.field_guide.entry_line_four");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_FIVE = ModUtil.tTC("procompsognathus.field_guide.entry_line_five");
	public static final ITextComponent PROCOMPSOGNATHUS_ENTRY_LINE_SIX = ModUtil.tTC("procompsognathus.field_guide.entry_line_six");
	public static final ITextComponent PROCOMPSOGNATHUS_DANGER = ModUtil.tTC("procompsognathus.field_guide.danger");
	public static final ITextComponent PROCOMPSOGNATHUS_DIET = ModUtil.tTC("procompsognathus.field_guide.diet");
	public static final ITextComponent PROCOMPSOGNATHUS_TYPE = ModUtil.tTC("procompsognathus.field_guide.type");
	public static final ITextComponent PROCOMPSOGNATHUS_TIME_ERA = ModUtil.tTC("procompsognathus.field_guide.time_era");
	
	public static final ITextComponent RHINESUCHUS_ENTRY_NAME = ModUtil.tTC("rhinesuchus.field_guide.name");
	public static final ITextComponent RHINESUCHUS_ENTRY_SPECIES_NAME = ModUtil.tTC("rhinesuchus.field_guide.species_name");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_ONE = ModUtil.tTC("rhinesuchus.field_guide.entry_line_one");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_TWO = ModUtil.tTC("rhinesuchus.field_guide.entry_line_two");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_THREE = ModUtil.tTC("rhinesuchus.field_guide.entry_line_three");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_FOUR = ModUtil.tTC("rhinesuchus.field_guide.entry_line_four");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_FIVE = ModUtil.tTC("rhinesuchus.field_guide.entry_line_five");
	public static final ITextComponent RHINESUCHUS_ENTRY_LINE_SIX = ModUtil.tTC("rhinesuchus.field_guide.entry_line_six");
	public static final ITextComponent RHINESUCHUS_DANGER = ModUtil.tTC("rhinesuchus.field_guide.danger");
	public static final ITextComponent RHINESUCHUS_DIET = ModUtil.tTC("rhinesuchus.field_guide.diet");
	public static final ITextComponent RHINESUCHUS_TYPE = ModUtil.tTC("rhinesuchus.field_guide.type");
	public static final ITextComponent RHINESUCHUS_TIME_ERA = ModUtil.tTC("rhinesuchus.field_guide.time_era");
	
	public static final ITextComponent DIMETRODON_ENTRY_NAME = ModUtil.tTC("dimetrodon.field_guide.name");
	public static final ITextComponent DIMETRODON_ENTRY_SPECIES_NAME = ModUtil.tTC("dimetrodon.field_guide.species_name");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_ONE = ModUtil.tTC("dimetrodon.field_guide.entry_line_one");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_TWO = ModUtil.tTC("dimetrodon.field_guide.entry_line_two");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_THREE = ModUtil.tTC("dimetrodon.field_guide.entry_line_three");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_FOUR = ModUtil.tTC("dimetrodon.field_guide.entry_line_four");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_FIVE = ModUtil.tTC("dimetrodon.field_guide.entry_line_five");
	public static final ITextComponent DIMETRODON_ENTRY_LINE_SIX = ModUtil.tTC("dimetrodon.field_guide.entry_line_six");
	public static final ITextComponent DIMETRODON_DANGER = ModUtil.tTC("dimetrodon.field_guide.danger");
	public static final ITextComponent DIMETRODON_DIET = ModUtil.tTC("dimetrodon.field_guide.diet");
	public static final ITextComponent DIMETRODON_TYPE = ModUtil.tTC("dimetrodon.field_guide.type");
	public static final ITextComponent DIMETRODON_TIME_ERA = ModUtil.tTC("dimetrodon.field_guide.time_era");
	
	public static final ITextComponent EDAPHOSAURUS_ENTRY_NAME = ModUtil.tTC("edaphosaurus.field_guide.name");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("edaphosaurus.field_guide.species_name");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("edaphosaurus.field_guide.entry_line_one");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("edaphosaurus.field_guide.entry_line_two");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("edaphosaurus.field_guide.entry_line_three");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("edaphosaurus.field_guide.entry_line_four");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("edaphosaurus.field_guide.entry_line_five");
	public static final ITextComponent EDAPHOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("edaphosaurus.field_guide.entry_line_six");
	public static final ITextComponent EDAPHOSAURUS_DANGER = ModUtil.tTC("edaphosaurus.field_guide.danger");
	public static final ITextComponent EDAPHOSAURUS_DIET = ModUtil.tTC("edaphosaurus.field_guide.diet");
	public static final ITextComponent EDAPHOSAURUS_TYPE = ModUtil.tTC("edaphosaurus.field_guide.type");
	public static final ITextComponent EDAPHOSAURUS_TIME_ERA = ModUtil.tTC("edaphosaurus.field_guide.time_era");
	
	public static final ITextComponent GORGONOPS_ENTRY_NAME = ModUtil.tTC("gorgonops.field_guide.name");
	public static final ITextComponent GORGONOPS_ENTRY_SPECIES_NAME = ModUtil.tTC("gorgonops.field_guide.species_name");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_ONE = ModUtil.tTC("gorgonops.field_guide.entry_line_one");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_TWO = ModUtil.tTC("gorgonops.field_guide.entry_line_two");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_THREE = ModUtil.tTC("gorgonops.field_guide.entry_line_three");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_FOUR = ModUtil.tTC("gorgonops.field_guide.entry_line_four");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_FIVE = ModUtil.tTC("gorgonops.field_guide.entry_line_five");
	public static final ITextComponent GORGONOPS_ENTRY_LINE_SIX = ModUtil.tTC("gorgonops.field_guide.entry_line_six");
	public static final ITextComponent GORGONOPS_DANGER = ModUtil.tTC("gorgonops.field_guide.danger");
	public static final ITextComponent GORGONOPS_DIET = ModUtil.tTC("gorgonops.field_guide.diet");
	public static final ITextComponent GORGONOPS_TYPE = ModUtil.tTC("gorgonops.field_guide.type");
	public static final ITextComponent GORGONOPS_TIME_ERA = ModUtil.tTC("gorgonops.field_guide.time_era");
	
	public static final ITextComponent CARNOTAURUS_ENTRY_NAME = ModUtil.tTC("carnotaurus.field_guide.name");
	public static final ITextComponent CARNOTAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("carnotaurus.field_guide.species_name");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_ONE = ModUtil.tTC("carnotaurus.field_guide.entry_line_one");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_TWO = ModUtil.tTC("carnotaurus.field_guide.entry_line_two");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_THREE = ModUtil.tTC("carnotaurus.field_guide.entry_line_three");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("carnotaurus.field_guide.entry_line_four");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("carnotaurus.field_guide.entry_line_five");
	public static final ITextComponent CARNOTAURUS_ENTRY_LINE_SIX = ModUtil.tTC("carnotaurus.field_guide.entry_line_six");
	public static final ITextComponent CARNOTAURUS_DANGER = ModUtil.tTC("carnotaurus.field_guide.danger");
	public static final ITextComponent CARNOTAURUS_DIET = ModUtil.tTC("carnotaurus.field_guide.diet");
	public static final ITextComponent CARNOTAURUS_TYPE = ModUtil.tTC("carnotaurus.field_guide.type");
	public static final ITextComponent CARNOTAURUS_TIME_ERA = ModUtil.tTC("carnotaurus.field_guide.time_era");
	
	public static final ITextComponent TYRANNOSAURUS_ENTRY_NAME = ModUtil.tTC("tyrannosaurus.field_guide.name");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("tyrannosaurus.field_guide.species_name");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_one");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_two");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_three");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_four");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_five");
	public static final ITextComponent TYRANNOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("tyrannosaurus.field_guide.entry_line_six");
	public static final ITextComponent TYRANNOSAURUS_DANGER = ModUtil.tTC("tyrannosaurus.field_guide.danger");
	public static final ITextComponent TYRANNOSAURUS_DIET = ModUtil.tTC("tyrannosaurus.field_guide.diet");
	public static final ITextComponent TYRANNOSAURUS_TYPE = ModUtil.tTC("tyrannosaurus.field_guide.type");
	public static final ITextComponent TYRANNOSAURUS_TIME_ERA = ModUtil.tTC("tyrannosaurus.field_guide.time_era");
	
	public static final ITextComponent ALLOSAURUS_ENTRY_NAME = ModUtil.tTC("allosaurus.field_guide.name");
	public static final ITextComponent ALLOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("allosaurus.field_guide.species_name");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("allosaurus.field_guide.entry_line_one");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("allosaurus.field_guide.entry_line_two");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("allosaurus.field_guide.entry_line_three");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("allosaurus.field_guide.entry_line_four");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("allosaurus.field_guide.entry_line_five");
	public static final ITextComponent ALLOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("allosaurus.field_guide.entry_line_six");
	public static final ITextComponent ALLOSAURUS_DANGER = ModUtil.tTC("allosaurus.field_guide.danger");
	public static final ITextComponent ALLOSAURUS_DIET = ModUtil.tTC("allosaurus.field_guide.diet");
	public static final ITextComponent ALLOSAURUS_TYPE = ModUtil.tTC("allosaurus.field_guide.type");
	public static final ITextComponent ALLOSAURUS_TIME_ERA = ModUtil.tTC("allosaurus.field_guide.time_era");
	
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_NAME = ModUtil.tTC("giganotosaurus.field_guide.name");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("giganotosaurus.field_guide.species_name");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("giganotosaurus.field_guide.entry_line_one");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("giganotosaurus.field_guide.entry_line_two");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("giganotosaurus.field_guide.entry_line_three");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("giganotosaurus.field_guide.entry_line_four");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("giganotosaurus.field_guide.entry_line_five");
	public static final ITextComponent GIGANOTOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("giganotosaurus.field_guide.entry_line_six");
	public static final ITextComponent GIGANOTOSAURUS_DANGER = ModUtil.tTC("giganotosaurus.field_guide.danger");
	public static final ITextComponent GIGANOTOSAURUS_DIET = ModUtil.tTC("giganotosaurus.field_guide.diet");
	public static final ITextComponent GIGANOTOSAURUS_TYPE = ModUtil.tTC("giganotosaurus.field_guide.type");
	public static final ITextComponent GIGANOTOSAURUS_TIME_ERA = ModUtil.tTC("giganotosaurus.field_guide.time_era");
	
	public static final ITextComponent SUCHOMIMUS_ENTRY_NAME = ModUtil.tTC("suchomimus.field_guide.name");
	public static final ITextComponent SUCHOMIMUS_ENTRY_SPECIES_NAME = ModUtil.tTC("suchomimus.field_guide.species_name");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_ONE = ModUtil.tTC("suchomimus.field_guide.entry_line_one");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_TWO = ModUtil.tTC("suchomimus.field_guide.entry_line_two");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_THREE = ModUtil.tTC("suchomimus.field_guide.entry_line_three");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_FOUR = ModUtil.tTC("suchomimus.field_guide.entry_line_four");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_FIVE = ModUtil.tTC("suchomimus.field_guide.entry_line_five");
	public static final ITextComponent SUCHOMIMUS_ENTRY_LINE_SIX = ModUtil.tTC("suchomimus.field_guide.entry_line_six");
	public static final ITextComponent SUCHOMIMUS_DANGER = ModUtil.tTC("suchomimus.field_guide.danger");
	public static final ITextComponent SUCHOMIMUS_DIET = ModUtil.tTC("suchomimus.field_guide.diet");
	public static final ITextComponent SUCHOMIMUS_TYPE = ModUtil.tTC("suchomimus.field_guide.type");
	public static final ITextComponent SUCHOMIMUS_TIME_ERA = ModUtil.tTC("suchomimus.field_guide.time_era");
	
	public static final ITextComponent TETRACERATOPS_ENTRY_NAME = ModUtil.tTC("tetraceratops.field_guide.name");
	public static final ITextComponent TETRACERATOPS_ENTRY_SPECIES_NAME = ModUtil.tTC("tetraceratops.field_guide.species_name");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_ONE = ModUtil.tTC("tetraceratops.field_guide.entry_line_one");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_TWO = ModUtil.tTC("tetraceratops.field_guide.entry_line_two");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_THREE = ModUtil.tTC("tetraceratops.field_guide.entry_line_three");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_FOUR = ModUtil.tTC("tetraceratops.field_guide.entry_line_four");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_FIVE = ModUtil.tTC("tetraceratops.field_guide.entry_line_five");
	public static final ITextComponent TETRACERATOPS_ENTRY_LINE_SIX = ModUtil.tTC("tetraceratops.field_guide.entry_line_six");
	public static final ITextComponent TETRACERATOPS_DANGER = ModUtil.tTC("tetraceratops.field_guide.danger");
	public static final ITextComponent TETRACERATOPS_DIET = ModUtil.tTC("tetraceratops.field_guide.diet");
	public static final ITextComponent TETRACERATOPS_TYPE = ModUtil.tTC("tetraceratops.field_guide.type");
	public static final ITextComponent TETRACERATOPS_TIME_ERA = ModUtil.tTC("tetraceratops.field_guide.time_era");
		
	public static final ITextComponent GREAT_AUK_ENTRY_NAME = ModUtil.tTC("great_auk.field_guide.name");
	public static final ITextComponent GREAT_AUK_ENTRY_SPECIES_NAME = ModUtil.tTC("great_auk.field_guide.species_name");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_ONE = ModUtil.tTC("great_auk.field_guide.entry_line_one");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_TWO = ModUtil.tTC("great_auk.field_guide.entry_line_two");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_THREE = ModUtil.tTC("great_auk.field_guide.entry_line_three");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_FOUR = ModUtil.tTC("great_auk.field_guide.entry_line_four");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_FIVE = ModUtil.tTC("great_auk.field_guide.entry_line_five");
	public static final ITextComponent GREAT_AUK_ENTRY_LINE_SIX = ModUtil.tTC("great_auk.field_guide.entry_line_six");
	public static final ITextComponent GREAT_AUK_DANGER = ModUtil.tTC("great_auk.field_guide.danger");
	public static final ITextComponent GREAT_AUK_DIET = ModUtil.tTC("great_auk.field_guide.diet");
	public static final ITextComponent GREAT_AUK_TYPE = ModUtil.tTC("great_auk.field_guide.type");
	public static final ITextComponent GREAT_AUK_TIME_ERA = ModUtil.tTC("great_auk.field_guide.time_era");
		
	public static final ITextComponent OURANOSAURUS_ENTRY_NAME = ModUtil.tTC("ouranosaurus.field_guide.name");
	public static final ITextComponent OURANOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("ouranosaurus.field_guide.species_name");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("ouranosaurus.field_guide.entry_line_one");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("ouranosaurus.field_guide.entry_line_two");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("ouranosaurus.field_guide.entry_line_three");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("ouranosaurus.field_guide.entry_line_four");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("ouranosaurus.field_guide.entry_line_five");
	public static final ITextComponent OURANOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("ouranosaurus.field_guide.entry_line_six");
	public static final ITextComponent OURANOSAURUS_DANGER = ModUtil.tTC("ouranosaurus.field_guide.danger");
	public static final ITextComponent OURANOSAURUS_DIET = ModUtil.tTC("ouranosaurus.field_guide.diet");
	public static final ITextComponent OURANOSAURUS_TYPE = ModUtil.tTC("ouranosaurus.field_guide.type");
	public static final ITextComponent OURANOSAURUS_TIME_ERA = ModUtil.tTC("ouranosaurus.field_guide.time_era");
		
	public static final ITextComponent FUKUIVENATOR_ENTRY_NAME = ModUtil.tTC("fukuivenator.field_guide.name");
	public static final ITextComponent FUKUIVENATOR_ENTRY_SPECIES_NAME = ModUtil.tTC("fukuivenator.field_guide.species_name");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_ONE = ModUtil.tTC("fukuivenator.field_guide.entry_line_one");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_TWO = ModUtil.tTC("fukuivenator.field_guide.entry_line_two");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_THREE = ModUtil.tTC("fukuivenator.field_guide.entry_line_three");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_FOUR = ModUtil.tTC("fukuivenator.field_guide.entry_line_four");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_FIVE = ModUtil.tTC("fukuivenator.field_guide.entry_line_five");
	public static final ITextComponent FUKUIVENATOR_ENTRY_LINE_SIX = ModUtil.tTC("fukuivenator.field_guide.entry_line_six");
	public static final ITextComponent FUKUIVENATOR_DANGER = ModUtil.tTC("fukuivenator.field_guide.danger");
	public static final ITextComponent FUKUIVENATOR_DIET = ModUtil.tTC("fukuivenator.field_guide.diet");
	public static final ITextComponent FUKUIVENATOR_TYPE = ModUtil.tTC("fukuivenator.field_guide.type");
	public static final ITextComponent FUKUIVENATOR_TIME_ERA = ModUtil.tTC("fukuivenator.field_guide.time_era");
		
	public static final ITextComponent PSITTACOSAURUS_ENTRY_NAME = ModUtil.tTC("psittacosaurus.field_guide.name");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("psittacosaurus.field_guide.species_name");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("psittacosaurus.field_guide.entry_line_one");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("psittacosaurus.field_guide.entry_line_two");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("psittacosaurus.field_guide.entry_line_three");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("psittacosaurus.field_guide.entry_line_four");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("psittacosaurus.field_guide.entry_line_five");
	public static final ITextComponent PSITTACOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("psittacosaurus.field_guide.entry_line_six");
	public static final ITextComponent PSITTACOSAURUS_DANGER = ModUtil.tTC("psittacosaurus.field_guide.danger");
	public static final ITextComponent PSITTACOSAURUS_DIET = ModUtil.tTC("psittacosaurus.field_guide.diet");
	public static final ITextComponent PSITTACOSAURUS_TYPE = ModUtil.tTC("psittacosaurus.field_guide.type");
	public static final ITextComponent PSITTACOSAURUS_TIME_ERA = ModUtil.tTC("psittacosaurus.field_guide.time_era");
		
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_NAME = ModUtil.tTC("cryolophosaurus.field_guide.name");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("cryolophosaurus.field_guide.species_name");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_one");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_two");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_three");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_four");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_five");
	public static final ITextComponent CRYOLOPHOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("cryolophosaurus.field_guide.entry_line_six");
	public static final ITextComponent CRYOLOPHOSAURUS_DANGER = ModUtil.tTC("cryolophosaurus.field_guide.danger");
	public static final ITextComponent CRYOLOPHOSAURUS_DIET = ModUtil.tTC("cryolophosaurus.field_guide.diet");
	public static final ITextComponent CRYOLOPHOSAURUS_TYPE = ModUtil.tTC("cryolophosaurus.field_guide.type");
	public static final ITextComponent CRYOLOPHOSAURUS_TIME_ERA = ModUtil.tTC("cryolophosaurus.field_guide.time_era");
	
	public static final ITextComponent OSTROMIA_ENTRY_NAME = ModUtil.tTC("ostromia.field_guide.name");
	public static final ITextComponent OSTROMIA_ENTRY_SPECIES_NAME = ModUtil.tTC("ostromia.field_guide.species_name");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_ONE = ModUtil.tTC("ostromia.field_guide.entry_line_one");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_TWO = ModUtil.tTC("ostromia.field_guide.entry_line_two");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_THREE = ModUtil.tTC("ostromia.field_guide.entry_line_three");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_FOUR = ModUtil.tTC("ostromia.field_guide.entry_line_four");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_FIVE = ModUtil.tTC("ostromia.field_guide.entry_line_five");
	public static final ITextComponent OSTROMIA_ENTRY_LINE_SIX = ModUtil.tTC("ostromia.field_guide.entry_line_six");
	public static final ITextComponent OSTROMIA_DANGER = ModUtil.tTC("ostromia.field_guide.danger");
	public static final ITextComponent OSTROMIA_DIET = ModUtil.tTC("ostromia.field_guide.diet");
	public static final ITextComponent OSTROMIA_TYPE = ModUtil.tTC("ostromia.field_guide.type");
	public static final ITextComponent OSTROMIA_TIME_ERA = ModUtil.tTC("ostromia.field_guide.time_era");
	
	public static final ITextComponent PROTOSUCHUS_ENTRY_NAME = ModUtil.tTC("protosuchus.field_guide.name");
	public static final ITextComponent PROTOSUCHUS_ENTRY_SPECIES_NAME = ModUtil.tTC("protosuchus.field_guide.species_name");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_ONE = ModUtil.tTC("protosuchus.field_guide.entry_line_one");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_TWO = ModUtil.tTC("protosuchus.field_guide.entry_line_two");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_THREE = ModUtil.tTC("protosuchus.field_guide.entry_line_three");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_FOUR = ModUtil.tTC("protosuchus.field_guide.entry_line_four");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_FIVE = ModUtil.tTC("protosuchus.field_guide.entry_line_five");
	public static final ITextComponent PROTOSUCHUS_ENTRY_LINE_SIX = ModUtil.tTC("protosuchus.field_guide.entry_line_six");
	public static final ITextComponent PROTOSUCHUS_DANGER = ModUtil.tTC("protosuchus.field_guide.danger");
	public static final ITextComponent PROTOSUCHUS_DIET = ModUtil.tTC("protosuchus.field_guide.diet");
	public static final ITextComponent PROTOSUCHUS_TYPE = ModUtil.tTC("protosuchus.field_guide.type");
	public static final ITextComponent PROTOSUCHUS_TIME_ERA = ModUtil.tTC("protosuchus.field_guide.time_era");
	
	public static final ITextComponent DIICTODON_ENTRY_NAME = ModUtil.tTC("diictodon.field_guide.name");
	public static final ITextComponent DIICTODON_ENTRY_SPECIES_NAME = ModUtil.tTC("diictodon.field_guide.species_name");
	public static final ITextComponent DIICTODON_ENTRY_LINE_ONE = ModUtil.tTC("diictodon.field_guide.entry_line_one");
	public static final ITextComponent DIICTODON_ENTRY_LINE_TWO = ModUtil.tTC("diictodon.field_guide.entry_line_two");
	public static final ITextComponent DIICTODON_ENTRY_LINE_THREE = ModUtil.tTC("diictodon.field_guide.entry_line_three");
	public static final ITextComponent DIICTODON_ENTRY_LINE_FOUR = ModUtil.tTC("diictodon.field_guide.entry_line_four");
	public static final ITextComponent DIICTODON_ENTRY_LINE_FIVE = ModUtil.tTC("diictodon.field_guide.entry_line_five");
	public static final ITextComponent DIICTODON_ENTRY_LINE_SIX = ModUtil.tTC("diictodon.field_guide.entry_line_six");
	public static final ITextComponent DIICTODON_DANGER = ModUtil.tTC("diictodon.field_guide.danger");
	public static final ITextComponent DIICTODON_DIET = ModUtil.tTC("diictodon.field_guide.diet");
	public static final ITextComponent DIICTODON_TYPE = ModUtil.tTC("diictodon.field_guide.type");
	public static final ITextComponent DIICTODON_TIME_ERA = ModUtil.tTC("diictodon.field_guide.time_era");
	
	public static final ITextComponent KENTROSAURUS_ENTRY_NAME = ModUtil.tTC("kentrosaurus.field_guide.name");
	public static final ITextComponent KENTROSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("kentrosaurus.field_guide.species_name");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("kentrosaurus.field_guide.entry_line_one");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("kentrosaurus.field_guide.entry_line_two");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("kentrosaurus.field_guide.entry_line_three");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("kentrosaurus.field_guide.entry_line_four");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("kentrosaurus.field_guide.entry_line_five");
	public static final ITextComponent KENTROSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("kentrosaurus.field_guide.entry_line_six");
	public static final ITextComponent KENTROSAURUS_DANGER = ModUtil.tTC("kentrosaurus.field_guide.danger");
	public static final ITextComponent KENTROSAURUS_DIET = ModUtil.tTC("kentrosaurus.field_guide.diet");
	public static final ITextComponent KENTROSAURUS_TYPE = ModUtil.tTC("kentrosaurus.field_guide.type");
	public static final ITextComponent KENTROSAURUS_TIME_ERA = ModUtil.tTC("kentrosaurus.field_guide.time_era");
	
	public static final ITextComponent CHILESAURUS_ENTRY_NAME = ModUtil.tTC("chilesaurus.field_guide.name");
	public static final ITextComponent CHILESAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("chilesaurus.field_guide.species_name");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_ONE = ModUtil.tTC("chilesaurus.field_guide.entry_line_one");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_TWO = ModUtil.tTC("chilesaurus.field_guide.entry_line_two");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_THREE = ModUtil.tTC("chilesaurus.field_guide.entry_line_three");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("chilesaurus.field_guide.entry_line_four");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("chilesaurus.field_guide.entry_line_five");
	public static final ITextComponent CHILESAURUS_ENTRY_LINE_SIX = ModUtil.tTC("chilesaurus.field_guide.entry_line_six");
	public static final ITextComponent CHILESAURUS_DANGER = ModUtil.tTC("chilesaurus.field_guide.danger");
	public static final ITextComponent CHILESAURUS_DIET = ModUtil.tTC("chilesaurus.field_guide.diet");
	public static final ITextComponent CHILESAURUS_TYPE = ModUtil.tTC("chilesaurus.field_guide.type");
	public static final ITextComponent CHILESAURUS_TIME_ERA = ModUtil.tTC("chilesaurus.field_guide.time_era");
	
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_NAME = ModUtil.tTC("liaoningosaurus.field_guide.name");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_SPECIES_NAME = ModUtil.tTC("liaoningosaurus.field_guide.species_name");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_ONE = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_one");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_TWO = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_two");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_THREE = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_three");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_FOUR = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_four");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_FIVE = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_five");
	public static final ITextComponent LIAONINGOSAURUS_ENTRY_LINE_SIX = ModUtil.tTC("liaoningosaurus.field_guide.entry_line_six");
	public static final ITextComponent LIAONINGOSAURUS_DANGER = ModUtil.tTC("liaoningosaurus.field_guide.danger");
	public static final ITextComponent LIAONINGOSAURUS_DIET = ModUtil.tTC("liaoningosaurus.field_guide.diet");
	public static final ITextComponent LIAONINGOSAURUS_TYPE = ModUtil.tTC("liaoningosaurus.field_guide.type");
	public static final ITextComponent LIAONINGOSAURUS_TIME_ERA = ModUtil.tTC("liaoningosaurus.field_guide.time_era");
}
